services:
  backend:
    build: 
      context: ./StockWebApp
    ports:
      - "3001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<YOUR PASSWORD>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/StockWebApp.pfx
    volumes:
      - .\httpcert:/https/
  frontend:
    build:
      context: ./stock-web-app
    ports:
      - "3000:80"
      